version: '3.8'

services:
  # --- FAZ 0: GÖZLEMLENEBİLİRLİK YIĞINI ---
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
    networks:
      - firefighter_net

  grafana:
    image: grafana/grafana-oss:9.5.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - firefighter_net

  # --- FAZ 1 & 2: GÜVENLİK YIĞINI ---
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.3
    container_name: wazuh-indexer
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - firefighter_net

  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.3
    container_name: wazuh-manager
    restart: unless-stopped
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - ./wazuh_manager_data/etc:/var/ossec/etc
      - ./wazuh_manager_data/logs:/var/ossec/logs
    networks:
      - firefighter_net
    depends_on:
      - wazuh.indexer

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.3
    container_name: wazuh-dashboard
    restart: unless-stopped
    ports:
      - "443:5601"
    environment:
      - "OPENSEARCH_HOSTS=https://wazuh.indexer:9200"
    networks:
      - firefighter_net
    depends_on:
      - wazuh.indexer

  # --- FAZ 1: CTI PLATFORMU ---
  misp-db:
    image: mariadb:10.11
    container_name: misp-db
    restart: unless-stopped
    volumes:
      - misp_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MISP_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=${MISP_DB_USER_PASSWORD}
    networks:
      - firefighter_net

  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:latest
    container_name: misp-core
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8880:80"
    networks:
      - firefighter_net
    depends_on:
      misp-db:
        condition: service_healthy

volumes:
  prometheus_data:
  grafana_data:
  wazuh_indexer_data:
  wazuh_manager_data:
  misp_db_data:

networks:
  firefighter_net:
    driver: bridge
